# Login - Logout
security_login:
  path: "/login"
  controller: Capersys\UserBundle\Controller\SecurityController::login
security_logout:
  path: "/logout"

# Register
security_register:
  path: "/register"
  controller: Capersys\UserBundle\Controller\SecurityController::register
security_register_confirm:
  path: "/register/{token}"
  controller: Capersys\UserBundle\Controller\SecurityController::registerConfirm

# Resetting
security_resetting:
  path: "/resetting"
  controller: Capersys\UserBundle\Controller\SecurityController::resetting
security_resetting_password:
  path: "/resetting/{token}"
  controller: Capersys\UserBundle\Controller\SecurityController::resettingPassword
